package com.example.jdbcdemo.service;

import java.sql.*;

import com.example.jdbcdemo.domain.Company;

public class CompanyManager {

	private Connection connection;
	private Statement statement;
	
	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	private String createTableCompany = "CREATE TABLE Company(id bigint GENERATED BY DEFAULT AS IDENTITY, name varchar(100))";
	
	private PreparedStatement addCompanyStmt;
	private PreparedStatement deleteAllCompaniesStmt;
	private PreparedStatement getAllCompaniesStmt;
	public CompanyManager(){
		try{
			
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();
			
			ResultSet rs = connection.getMetaData().getTables(null, null, null,
					null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Company".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(createTableCompany);	
			
			addCompanyStmt = connection
					.prepareStatement("INSERT INTO Company (name) VALUES (?)");
			deleteAllCompaniesStmt = connection
					.prepareStatement("DELETE FROM Company");
			getAllCompaniesStmt = connection
					.prepareStatement("SELECT id, name FROM Company");
			
		} catch (SQLException e){
			e.printStackTrace();
		}
	}
	
	// Package scope
	Connection getConnection(){
		return connection;
	}
	public int addCompany(Company company){
		int count = 0;
		try {
			addCompanyStmt.setString(1, company.getName());

			count = addCompanyStmt.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return count;		
	}
}
